# Generated by Django 4.2.2 on 2023-06-25 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image_url', models.CharField(max_length=2083)),
                ('desc', models.CharField(max_length=500)),
                ('game_type', models.CharField(max_length=50)),
            ],
        ),
    ]
