# Generated by Django 4.2.2 on 2023-06-25 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_game_popularity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='desc',
        ),
    ]
