# Generated by Django 4.2.2 on 2023-07-03 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_game_prize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='prize',
            field=models.FloatField(max_length=10),
        ),
    ]
