# Generated by Django 4.2.2 on 2023-06-25 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='dawnload_link',
            field=models.CharField(default=1, max_length=2083),
            preserve_default=False,
        ),
    ]
