# Generated by Django 4.2.2 on 2023-06-25 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_game_dawnload_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='popularity',
            field=models.IntegerField(default=1, max_length=1),
            preserve_default=False,
        ),
    ]
