# Generated by Django 4.2.2 on 2023-07-03 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_game_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='prize',
            field=models.IntegerField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
